version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fbclone # Set the default database name to fbclone
    ports:
      - "5432:5432" # Expose PostgreSQL port
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Expose Adminer port
