version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fbclone # Set the default database name to fbclone
    ports:
      - "5432:5432" # Expose PostgreSQL port
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Expose Adminer port
  # bun:
  #   depends_on:
  #     - db
  #   build:
  #     dockerfile: Dockerfile.yml
  #     context: .
  #   image: oven/bun:latest
  #   ports:
  #     - "3000:3000"
  #   working_dir: /backend
  #   # command: ["sh", "-c", "chmod u+x start.sh && ./start.sh"]
  #   # command: ["sh", "-c", "sleep 100"]
